Add Prehistoric style
OpenRCT2/OpenMusic pull request #25
Opened 2023-03-10 21:42 UTC by Flyxxpy

Add Prehistoric music style, make changes to readme.md

2023-03-10 21:46 UTC, karst commented on replacements/openrct2.music.prehistoric/object.json
> +                "name": "Flyxxpy - The Ancient Lands"
`"name": "The Ancient Lands",`
`"composer": "Flyxxpy"`

2023-03-10 21:50 UTC, karst commented
The file size of the flac file is about half the size I would have expected. Did you render it at 41000hz project rate rather than the 20500 that RCT uses? The converter will take care that the size is small when included, but it leaves the ability in the future to have "high quality" packs available as well as the soundtrack itself in full quality.

2023-03-10 22:05 UTC, Flyxxpy commented
I just changed the track to 44.1 kHz.

2023-03-10 22:21 UTC, Flyxxpy commented
I changed the data in the json file according to what you mentioned in your first comment.

2023-03-10 22:24 UTC, karst submitted a review, later dismissed

2023-03-13 23:07 UTC, karst commented
Could you also edit `openrct2.music.alternative.json` for me similar to how I have done here: https://github.com/OpenRCT2/OpenMusic/pull/21/files

2023-03-13 23:09 UTC, karst requested changes
See comment above.

2023-03-14 10:39 UTC, tupaschoal reviewed
I really like this one, in contrast I think it's even better and more epic than the original. It did feel to me though that the volume was a bit maxed out and "cutting" at the beginning, maybe it needs to be dampened a bit (?)

PS: Yes, I have very crappy speakers, but then, this makes for a good second opinion, since you folks probably have studio-grade audio equipment :D

2023-03-14 10:47 UTC, Flyxxpy commented
> I really like this one, in contrast I think it's even better and more epic than the original. It did feel to me though that the volume was a bit maxed out and "cutting" at the beginning, maybe it needs to be dampened a bit (?)
> 
> PS: Yes, I have very crappy speakers, but then, this makes for a good second opinion, since you folks probably have studio-grade audio equipment :D

I know what you're referring to, I had to add a maximizer and a limiter to the track, as its volume originally was way too low compared to all the other tracks. This also seemed to work quite a lot better than trying to use a compressor, though I don't know much more than the basics of mastering audio, so there are probably better ways to do this.

2023-03-14 11:59 UTC, Flyxxpy commented
> I really like this one, in contrast I think it's even better and more epic than the original. It did feel to me though that the volume was a bit maxed out and "cutting" at the beginning, maybe it needs to be dampened a bit (?)
> 
> PS: Yes, I have very crappy speakers, but then, this makes for a good second opinion, since you folks probably have studio-grade audio equipment :D

I improved the volume consistency of the track quite a bit, thanks for your input!

2023-03-14 19:14 UTC, karst commented
The new master seems to poke out some issues in the mix, there's some painful frequencies at 500hz and 2000hz, I'd probably also lower the sub slightly, perhaps by 3db. 130hz seems a tad muddy, perhaps the tom is clashing with a pad on the lowend, but only slightly. It also seems that the file is missing its tail moved from the end to the start (I think you just rendered the full song without tail, rather than re-rending it after placing the tail back to the front.

This is the EQ I applied and seems to work naturally.
![image](https://user-images.githubusercontent.com/1516893/225112809-631745a0-8b7e-4f10-a69f-d5765ea86291.png)

2023-03-16 23:13 UTC, tupaschoal commented
Hmm, I still get mixed feelings, feel like there is background noise, maybe it is the choir? How easy is it for you to attach a version here with the choir off?

2023-03-17 10:20 UTC, Flyxxpy commented
> Hmm, I still get mixed feelings, feel like there is background noise, maybe it is the choir? How easy is it for you to attach a version here with the choir off?

Does this work for you?
https://drive.google.com/file/d/1qruqfyoAmtvh7LHihc4E__Xmjqp1WKdv/view?usp=share_link

This does not have the EQ applied, though, as that was done by karst.

2023-03-20 13:39 UTC, tupaschoal commented
I love it that way!

2023-03-26 21:21 UTC, Flyxxpy commented
> I love it that way!

Thanks! The final version without choir and with the EQ applied is now commited.

2023-03-26 21:47 UTC, karst approved these changes

2023-03-30 00:06 UTC, tupaschoal approved these changes

2023-03-30 00:12 UTC, merged

2023-03-30 17:54 UTC, karst commented
Once I know if https://github.com/OpenRCT2/OpenRCT2/pull/19785 will get merged I'll make sure to create a new release.